dungeons:
  hoa:
    name: Halls of Atonement
    url: https://keystone.guru/routes/retail/halls-of-atonement
  gambit:
    name: Tazavesh So'Leahs - Gambit
    url: https://keystone.guru/routes/retail/tazavesh-so-leahs-gambit
  streets:
    name: Tazavesh So'Leahs - Streets
    url: https://keystone.guru/routes/retail/tazavesh-streets-of-wonder
  arak:
    name: Ara Kara City of Echoes
    url: https://keystone.guru/routes/retail/ara-kara-city-of-echoes
  flood:
    name: Operation - Floodgate
    url: https://keystone.guru/routes/retail/operation-floodgate
  priory:
    name: Priory of the Sacred Flame
    url: https://keystone.guru/routes/retail/priory-of-the-sacred-flame
  dawn:
    name: The Dawnbreaker
    url: https://keystone.guru/routes/retail/the-dawnbreaker
    